spring:
  profiles:
    active: test

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/com/xinghui/**/mybatis/**.xml

edu-eval:
  filter:
    white-list: /doc.html,/swagger-resources,/v2/api-docs,/error,/amg/auth/v1/login,/amg/auth/v1/register

jwt:
  overdue-time: 3600000
